name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build/release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/release launcher app
        uses: heliomarpm/action-electron-builder@v2.1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          args: --config ./build_configs/launcher.js

      - name: Build/release dedicated server app
        uses: heliomarpm/action-electron-builder@v2.1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          build_script_name: build:ds
          args: --config ./build_configs/dedicatedServer.js

